"""test

Revision ID: 12b0f2411d87
Revises: 
Create Date: 2024-02-05 21:45:24.680062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '12b0f2411d87'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelines',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(length=100),
                              server_default='', nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('steps',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('queue_name', sa.String(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('pipeline_step_association',
                    sa.Column('pipeline_id', sa.Integer(), nullable=False),
                    sa.Column('step_id', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['pipeline_id'],
                                            ['pipelines.id'], ),
                    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('pipeline_id', 'step_id',
                                        name='idx_unique_pipeline_step')
                    )
    op.create_table('resulttasks',
                    sa.Column('file_name', sa.String(), nullable=False),
                    sa.Column('top_left_x', sa.Integer(), nullable=True),
                    sa.Column('top_left_y', sa.Integer(), nullable=True),
                    sa.Column('width', sa.Integer(), nullable=True),
                    sa.Column('height', sa.Integer(), nullable=True),
                    sa.Column('conf', sa.Integer(), nullable=True),
                    sa.Column('label', sa.Integer(), nullable=True),
                    sa.Column('pipeline_id', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['pipeline_id'],
                                            ['pipelines.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resulttasks')
    op.drop_table('pipeline_step_association')
    op.drop_table('steps')
    op.drop_table('pipelines')
    # ### end Alembic commands ###
